export const FETCH_ARTICLES_LIST = 'FETCH_ARTICLES_LIST';
export const FETCH_ARTICLES_LIST_SUCCESS = 'FETCH_ARTICLES_LIST_SUCCESS';
export const FETCH_ARTICLES_LIST_FAIL = 'FETCH_ARTICLES_LIST_FAIL';
